CREATE DATABASE `GM_STORIES` /*!40100 COLLATE 'utf8mb4_general_ci' */

--          Table STORIES
DROP TABLE IF EXISTS STORIES;
CREATE TABLE STORIES(
    ID VARCHAR(20) COMMENT 'ID truyện' COLLATE 'utf8mb4_general_ci',
    TITLE NVARCHAR(200) NOT NULL COMMENT 'Tên truyện' COLLATE 'utf8mb3_general_ci',
    CONTENT_TYPE BINARY NOT NULL DEFAULT 1 COMMENT 'Thể loại truyện tranh/chữ. 1 - Truyện tranh   2 - Truyện chữ',
    FLAG_STATUS BINARY NOT NULL DEFAULT 1  COMMENT 'Trạng thái bị xóa/hiển thị của truyện. 1 - Active   0 - Inactive',
    PRIMARY KEY (`ID`) USING BTREE
)
COMMENT='Thông tin cơ bản của truyện'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;

--          Table STORIES_CHAPTERS
DROP TABLE IF EXISTS STORIES_CHAPTERS;
CREATE TABLE STORIES_CHAPTERS(
    CHAPTER_NUMBER BIGINT NOT NULL COMMENT 'Số thứ tự chương truyện',
    STORY_ID VARCHAR(20) NOT NULL COMMENT 'ID của truyện',
    LINK VARCHAR(200) COMMENT 'Đường link của chương truyện',
    CONTENT TEXT NOT NULL COMMENT 'Nội dung truyện, có thể là đường link các hình ảnh hoặc văn bản',
    UPDATE_DATE DATETIME COMMENT 'Thời gian update chương',
    VIEWS BIGINT NOT NULL DEFAULT 0 COMMENT 'Lượt xem chương',
    FLAG_STATUS BINARY NOT NULL DEFAULT 1 COMMENT 'Trạng thái hoạt động của chương. 1 - Active   0 - Inactive',
    SCOPE BINARY NOT NULL DEFAULT 1 COMMENT 'Phạm vi đọc của chương. 1 - Public   2 - Private (Mở khóa thì mới đọc được)'
)
COMMENT='Các chapters của truyện'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;

--          Table CATEGORIES
DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE CATEGORIES(
    ID VARCHAR(20) COMMENT 'ID danh mục',
    NAME VARCHAR(200) COMMENT 'Tên danh mục'
)
COMMENT='Tất cả danh mục truyện'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;

--          Table STORIES_CATEGORIES
DROP TABLE IF EXISTS STORIES_CATEGORIES;
CREATE TABLE STORIES_CATEGORIES(
    STORY_ID VARCHAR(20) COMMENT 'ID truyện',
    CATEGORY_ID VARCHAR(20) COMMENT 'ID danh mục'
)
COMMENT='Danh mục của từng truyện'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;


--          CONSTRAINTS
ALTER TABLE STORIES_CHAPTERS ADD CONSTRAINT FK_STORIES_CHAPTERS FOREIGN KEY (STORY_ID) REFERENCES STORIES(ID);
ALTER TABLE STORIES_CHAPTERS ADD CONSTRAINT PK_STORIES_CHAPTERS PRIMARY KEY (CHAPTER_NUMBER, STORY_ID, FLAG_STATUS);
ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID);
ALTER TABLE STORIES_CATEGORIES ADD CONSTRAINT FK_STORIES FOREIGN KEY (STORY_ID) REFERENCES STORIES(ID);
ALTER TABLE STORIES_CATEGORIES ADD CONSTRAINT FK_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID);

