#server.port: 8800
#gateway.allowed.hosts: "*"
#spring:
#  application:
#    name: GM-ADMIN
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true